CREATE TABLE IF NOT EXISTS person(
  id SERIAL PRIMARY KEY,
  name VARCHAR(124) NOT NULL,
  surname VARCHAR(124) NOT NULL,
  email VARCHAR(124) NOT NULL UNIQUE,
  password_hash VARCHAR NOT NULL,
  avatar_url VARCHAR(255),
  created TIMESTAMPTZ,
  updated TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS post(
  id SERIAL PRIMARY KEY,
  title VARCHAR(124) NOT NULL,
  text VARCHAR(5120) NOT NULL,
  tags TEXT [],
  image_url VARCHAR(255),
  views_count INTEGER DEFAULT 0,
  created TIMESTAMPTZ,
  user_id INTEGER,
  FOREIGN KEY (user_id) REFERENCES person (id)
);

